# Generated by Django 3.1 on 2020-09-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentas',
            name='nro_cuenta',
            field=models.IntegerField(default=1, unique=True, verbose_name='Número de Cuenta'),
            preserve_default=False,
        ),
    ]
