# Generated by Django 3.1.5 on 2021-02-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Código')),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.rubros')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.IntegerField(unique=True, verbose_name='Código Item')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('existencia', models.FloatField(verbose_name='Existencia')),
                ('item_suspendido', models.BooleanField(verbose_name='Item suspendido')),
                ('motivo_suspension', models.TextField(verbose_name='Motivo suspension')),
                ('deposito', models.IntegerField(verbose_name='Deposito')),
                ('codigo_barra', models.IntegerField(verbose_name='Código de barras')),
                ('observacion', models.TextField(verbose_name='Observaciones')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('stock_comprometido', models.FloatField(verbose_name='Stock Comprometido')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.rubros')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['nombre'],
            },
        ),
    ]
