# Generated by Django 3.1.3 on 2021-02-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='codigo_barra',
            field=models.IntegerField(null=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='deposito',
            field=models.IntegerField(null=True, verbose_name='Deposito'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='existencia',
            field=models.FloatField(null=True, verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='item_suspendido',
            field=models.BooleanField(default=False, null=True, verbose_name='Item suspendido'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='motivo_suspension',
            field=models.TextField(null=True, verbose_name='Motivo suspension'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.TextField(null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='observacion',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio',
            field=models.FloatField(null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.rubros'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='stock_comprometido',
            field=models.FloatField(null=True, verbose_name='Stock Comprometido'),
        ),
    ]
