# Generated by Django 3.1.3 on 2021-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210224_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='item_suspendido',
            field=models.BooleanField(blank=True, default=False, verbose_name='Item suspendido'),
        ),
    ]
