# Generated by Django 3.1.3 on 2021-02-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210225_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='item_suspendido',
            field=models.BooleanField(default=False, null=True, verbose_name='Item suspendido'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='motivo_suspension',
            field=models.TextField(blank=True, default=False, verbose_name='Motivo suspension'),
        ),
    ]
