# Generated by Django 3.1.3 on 2021-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210225_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='item_suspendido',
            field=models.BooleanField(null=True, verbose_name='Item suspendido'),
        ),
    ]
