# Generated by Django 3.1 on 2020-09-29 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha_del_asiento')),
                ('desctripcion', models.TextField(verbose_name='Descripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo_cuenta',
                'verbose_name_plural': 'Tipo_cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuenta', models.IntegerField(unique=True, verbose_name='Número de Cuenta')),
                ('nombre_cuenta', models.CharField(max_length=80, unique=True, verbose_name='Nombre de Cuenta')),
                ('recibe_saldo', models.BooleanField(default=True)),
                ('saldo_actual', models.FloatField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homepage.cuentas')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.tipo_cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta_asientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Debe'), ('H', 'Haber')], default='D', max_length=1)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('saldo_parcial', models.FloatField(blank=True, null=True)),
                ('id_asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.asientos')),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.cuentas')),
            ],
            options={
                'verbose_name': 'cuenta_asiento',
                'verbose_name_plural': 'cuentas_asientos',
                'ordering': ['id'],
            },
        ),
    ]
