# Generated by Django 3.1.1 on 2020-10-09 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asientoBorrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha_del_asiento')),
                ('descripcion', models.CharField(default='SIN_NOMBRE', max_length=255, verbose_name='Descripcion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cuenta_asientos',
            options={},
        ),
        migrations.CreateModel(
            name='cuenta_asientoBorrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Debe'), ('H', 'Haber')], default='D', max_length=1)),
                ('monto', models.FloatField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.asientoborrador')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.cuentas')),
            ],
            options={
                'verbose_name': 'cuenta_asiento',
                'verbose_name_plural': 'cuentas_asientos',
                'ordering': ['id'],
            },
        ),
    ]
