# Generated by Django 3.1.1 on 2020-10-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201009_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientoborrador',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha_del_asiento'),
        ),
    ]
