# Generated by Django 3.1.3 on 2021-01-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201009_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientoborrador',
            options={'ordering': ['id'], 'verbose_name': 'Asiento Borrador', 'verbose_name_plural': 'Asientos Borrador'},
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='saldo_actual',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
