# Generated by Django 3.1.5 on 2021-02-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210121_2052'),
        ('homepage', '0004_auto_20210128_2116'),
    ]

    operations = [
    ]
