# Generated by Django 3.1 on 2020-09-18 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200917_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha_del_asiento'),
        ),
    ]
