# Generated by Django 3.1.5 on 2021-02-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito_maximo', models.FloatField(blank=True, default=0, null=True)),
                ('estado_cliente', models.BooleanField(verbose_name='Estado de cliente')),
                ('tipo_cliente', models.CharField(max_length=1, verbose_name='Tipo de cliente')),
                ('categoria_iva', models.CharField(choices=[('G', 'General'), ('R', 'Reducido'), ('S', 'Superreducido'), ('E', 'Exento')], max_length=1, unique=True, verbose_name='Categoria IVA')),
                ('telefono', models.TextField(verbose_name='Telefono')),
                ('cuit', models.TextField(unique=True, verbose_name='CUIT')),
                ('e_mail', models.TextField(verbose_name='e-mail')),
                ('codigo_postal', models.IntegerField(verbose_name='Codigo postal')),
                ('fecha_nac', models.DateTimeField(null=True, verbose_name='Fecha del nacimiento')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('piso', models.IntegerField(verbose_name='Piso')),
                ('departamento', models.CharField(max_length=20, verbose_name='Departamento')),
                ('calle', models.TextField(verbose_name='Calle')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('codigo', models.IntegerField(unique=True, verbose_name='Codigo de cliente')),
                ('fecha_cre', models.DateTimeField(null=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['cuit'],
            },
        ),
    ]
