# Generated by Django 3.1 on 2020-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200917_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_asientos',
            name='monto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
