# Generated by Django 3.1 on 2020-09-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200918_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='codigo_asiento',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
