# Generated by Django 3.1 on 2020-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_asientos_codigo_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientos',
            name='codigo_asiento',
        ),
    ]
