# Generated by Django 3.1.5 on 2021-02-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('articles', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubros',
            name='subrubro',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='articulo',
            field=models.ManyToManyField(to='articles.Articulos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.clientes'),
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Rubros',
        ),
    ]
