# Generated by Django 3.1.3 on 2021-02-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210202_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha'),
        ),
    ]
