# Generated by Django 3.1.3 on 2021-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20210226_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.CharField(max_length=50, verbose_name='Cliente'),
        ),
    ]
